// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWTLcPC5cH9iAjM4NIWo8hZeqIK0PvS_0',
    appId: '1:1098788514565:web:04d0c227c142825c46256c',
    messagingSenderId: '1098788514565',
    projectId: 'holybibleandroid',
    authDomain: 'holybibleandroid.firebaseapp.com',
    databaseURL: 'https://holybibleandroid.firebaseio.com',
    storageBucket: 'holybibleandroid.appspot.com',
    measurementId: 'G-3DQB7WZY2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAquZFsugCWphdeaXDwC1kkCnBZSYjeFBI',
    appId: '1:1098788514565:android:846a77e3eb79053846256c',
    messagingSenderId: '1098788514565',
    projectId: 'holybibleandroid',
    databaseURL: 'https://holybibleandroid.firebaseio.com',
    storageBucket: 'holybibleandroid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jRlt8AjVY45_OsjLYnhp0-2VWQg2Wws',
    appId: '1:1098788514565:ios:d0adeb0c9b33b28c46256c',
    messagingSenderId: '1098788514565',
    projectId: 'holybibleandroid',
    databaseURL: 'https://holybibleandroid.firebaseio.com',
    storageBucket: 'holybibleandroid.appspot.com',
    androidClientId: '1098788514565-ab9rtm33vfjvsuvtf8dq9cadagic0bth.apps.googleusercontent.com',
    iosClientId: '1098788514565-sb3imoj9ehhtmvfjf98cuv6c3si3bm5j.apps.googleusercontent.com',
    iosBundleId: 'net.joostory.holybible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jRlt8AjVY45_OsjLYnhp0-2VWQg2Wws',
    appId: '1:1098788514565:ios:d0adeb0c9b33b28c46256c',
    messagingSenderId: '1098788514565',
    projectId: 'holybibleandroid',
    databaseURL: 'https://holybibleandroid.firebaseio.com',
    storageBucket: 'holybibleandroid.appspot.com',
    androidClientId: '1098788514565-ab9rtm33vfjvsuvtf8dq9cadagic0bth.apps.googleusercontent.com',
    iosClientId: '1098788514565-sb3imoj9ehhtmvfjf98cuv6c3si3bm5j.apps.googleusercontent.com',
    iosBundleId: 'net.joostory.holybible',
  );
}
